name: spree
version: 0.0.0
repository: https://github.com/naxmefy/spree
homepage: https://github.com/naxmefy/spree
description: >
  Spree Commerce API SDK for authentication, platform and storefront API.

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
